/**************************************************************************************************
Purpose     : This script creates all the required tables in the 'bronze' schema for the 
               Snowflake project. Tables are loaded as-is from the internal stage (CSV files), 
               forming the Bronze Layer (raw data).
               
               The purpose of this layer is to:
               - Store source data with minimal transformations.
               - Serve as a foundation for downstream cleansing, modelling, and analytics via the
                 Silver and Gold layers.
CALL CREATE_BRONZE_TABLES();
**************************************************************************************************/

CREATE OR REPLACE PROCEDURE CREATE_BRONZE_TABLES()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

    ----------------------------------------------------------------
    -- BRONZE.ORDERS
    ----------------------------------------------------------------
    CREATE OR REPLACE TABLE MF_DWH.BRONZE.ORDERS (
        ORDERID VARCHAR,
        ORDERREFERENCE VARCHAR,
        ORDERINVOICE VARCHAR,
        ORDERTYPEID VARCHAR,
        ORDERDATE VARCHAR,
        ORDERUSERID VARCHAR,
        ORDERAMOUNT VARCHAR,
        ORDERTAX VARCHAR,
        ORDERDISCOUNT VARCHAR,
        ORDERCARDAMOUNT VARCHAR,
        ORDERCASHAMOUNT VARCHAR,
        ORDERMODEOFPAYMENTID VARCHAR,
        ORDERADDRESSID VARCHAR,
        ORDERSTATUSID VARCHAR,
        ORDERDELIVERYBY VARCHAR,
        ORDERDELIVERYLOCATIONID VARCHAR,
        ORDERDELIVERYSLOTID VARCHAR,
        ORDERSUPPLIERID VARCHAR,
        ORDERSHIPPINGID VARCHAR,
        ORDERSHIPPINGCHARGE VARCHAR,
        ORDERNETAMOUNT VARCHAR,
        ORDERPOINTSGAINED VARCHAR,
        ORDERPOINTSREDEEMED VARCHAR,
        ORDERADDEDBY VARCHAR,
        ORDERSTOREID VARCHAR,
        ORDERUPDATEDBY VARCHAR,
        ORDERUPDATEON VARCHAR,
        ORDERSTOCKID VARCHAR,
        ORDERCOURIERCHARGEHELDUPTO VARCHAR,
        ORDERHANDLINGCHARGE VARCHAR,
        ORDERHANDLINGCHARGEPAYOUTID VARCHAR,
        ORDERLATEPAYMENT VARCHAR,
        ORDERLATEPAYMENTDATE VARCHAR,
        ORDERPAYMENTRECEIPTID VARCHAR,
        ORDERCLUBID VARCHAR,
        ORDERRETURNID VARCHAR,
        ORDERSHIPPINGISFREE VARCHAR,
        ORDERASSIGNEDDATE VARCHAR,
        ORDEROUTFORDELIVERYDATE VARCHAR,
        ORDERDELIVERYDATE VARCHAR,
        ORDERCANCELACTION VARCHAR,
        ORDERPAYCOUNT VARCHAR
    );

    ----------------------------------------------------------------
    -- BRONZE.ORDERLINES
    ----------------------------------------------------------------
    CREATE OR REPLACE TABLE MF_DWH.BRONZE.ORDERLINES (
        ORDERLINEID VARCHAR,
        ORDERLINEORDERID VARCHAR,
        ORDERLINEPRODUCTID VARCHAR,
        ORDERLINEPRODUCTSTOCKID VARCHAR,
        ORDERLINEPRICE VARCHAR,
        ORDERLINEQTY VARCHAR,
        ORDERLINEAMOUNT VARCHAR,
        ORDERLINETAX VARCHAR,
        ORDERLINEDISCOUNT VARCHAR,
        ORDERLINENETAMOUNT VARCHAR,
        ORDERLINESTATUS VARCHAR,
        ORDERLINEPOINTSGAINED VARCHAR,
        ORDERLINEUPDATEDBY VARCHAR,
        ORDERLINEUPDATEON VARCHAR,
        ORDERLINEPRODUCTOPTIONID VARCHAR,
        ORDERLINEFLASHSALEID VARCHAR
    );

    ----------------------------------------------------------------
    -- BRONZE.PRODUCT
    ----------------------------------------------------------------
    CREATE OR REPLACE TABLE MF_DWH.BRONZE.PRODUCT (
        PRODUCTID NUMBER,
        PRODUCTTYPE NUMBER,
        PRODUCTNAME VARCHAR,
        PRODUCTSKU VARCHAR,
        PRODUCTCARTDESC VARCHAR,
        PRODUCTSHORTDESC VARCHAR,
        PRODUCTLONGDESC VARCHAR,
        PRODUCTTHUMBID NUMBER,
        PRODUCTIMAGEID NUMBER,
        PRODUCTADDEDON TIMESTAMP_NTZ,
        PRODUCTADDEDBY NUMBER,
        PRODUCTDENOMINATIONID NUMBER,
        PRODUCTREMOVEDON TIMESTAMP_NTZ,
        PRODUCTREMOVEDBY NUMBER,
        PRODUCTURLSLUG VARCHAR,
        PRODUCTREPACKED BOOLEAN,
        PRODUCTREPACKEDFROM NUMBER,
        PRODUCTSUPPLIERID NUMBER,
        PRODUCTSEOTITLE VARCHAR,
        PRODUCTSEODESCRIPTIONS VARCHAR,
        PRODUCTSEOKEYWORDS VARCHAR,
        PRODUCTPURCHASEPOINTS NUMBER(12,2),
        PRODUCTREDEEMPOINTS NUMBER(12,2),
        PRODUCTVIEWCOUNT NUMBER,
        PRODUCTTAXID NUMBER,
        PRODUCTPERORDERMINQTY NUMBER(12,3),
        PRODUCTPERORDERMAXQTY NUMBER(12,3),
        PRODUCTBARCODE VARCHAR,
        PRODUCTHSNID NUMBER,
        PRODUCTHSNCODE VARCHAR,
        PRODUCTORIGIN VARCHAR,
        PRODUCTMSLQTY NUMBER(12,3),
        PRODUCTVIDEODEMOLINK VARCHAR,
        PRODUCTBROCHUREMEDIAID NUMBER,
        PRODUCTLASTPOMEDIAID NUMBER,
        PRODUCTDELIVERYRETURNPERIOD NUMBER,
        PRODUCTNEAREXPIRYRETURNPERIOD NUMBER,
        PRODUCTPRESCRIPTIONYN BOOLEAN,
        PRODUCTDELIVERYRETURNEXCHANGE VARCHAR,
        PRODUCTSPECIALCATEGORYID NUMBER,
        PRODUCTSPECIALITYID NUMBER,
        PRODUCTUSAGETYPEID NUMBER,
        PRODUCTPREMIUMYN BOOLEAN,
        PRODUCTLENGTH NUMBER(12,3),
        PRODUCTBREADTH NUMBER(12,3),
        PRODCUTHEIGHT NUMBER(12,3),
        PRODCUTWEIGHT NUMBER(12,3),
        PRODUCTCASHBACKPERCENTAGE NUMBER(10,2),
        PRODUCTREJECTEDON TIMESTAMP_NTZ,
        PRODUCTREJECTEDBY NUMBER,
        PRODUCTAPPROVEDON TIMESTAMP_NTZ,
        PRODUCTAPPROVEDBY NUMBER,
        PRODUCTSOLDOUT BOOLEAN,
        PRODUCTSTOCKDISPLAY BOOLEAN,
        PRODUCTCLASSIFICATION NUMBER,
        PRODUCTWEIGHTPERCENTAGE NUMBER(10,2),
        PRODUCTUPDATEDBY NUMBER,
        PRODUCTUPDATEDON TIMESTAMP_NTZ,
        PRODUCTPRIORITYSORT NUMBER,
        PRODUCTUOM VARCHAR,
        PRODUCTCOMBO BOOLEAN,
        PRODUCTPERKGCOUNT NUMBER(12,3),
        PRODUCTKGPERCOUNT NUMBER(12,3)
    );

    ----------------------------------------------------------------
    -- BRONZE.PRODUCTSTOCKS
    ----------------------------------------------------------------
    CREATE OR REPLACE TABLE MF_DWH.BRONZE.PRODUCTSTOCKS (
        STOCKID NUMBER,
        STOCKPRODUCTID NUMBER,
        STOCKBATCH VARCHAR,
        STOCKDOM DATE,
        STOCKEXPIRY DATE,
        STOCKUNITPRICE NUMBER(12,2),
        STOCKINVOICEPRICE NUMBER(12,2),
        STOCKQTY NUMBER(12,3),
        STOCKLOCATION VARCHAR,
        STOCKSTATUS NUMBER,
        STOCKWHOLESALEPRICE NUMBER(12,2),
        STOCKDEALERPRICE NUMBER(12,2),
        STOCKPRODUCTOPTIONID NUMBER,
        STOCKSTOREID NUMBER,
        STOCKPRICECURRENCYID NUMBER
    );

    ----------------------------------------------------------------
    -- BRONZE.PRODUCT_OPTIONS
    ----------------------------------------------------------------
    CREATE OR REPLACE TABLE MF_DWH.BRONZE.PRODUCT_OPTIONS (
        PRODUCTOPTIONID NUMBER,
        PRODUCTPACKAGEID NUMBER,
        PRODUCTOPTIONPRODUCTID NUMBER,
        PRODUCTOPTIONSID NUMBER,
        PRODUCTOPTIONADDEDON TIMESTAMP_NTZ,
        PRODUCTOPTIONADDEDBY NUMBER,
        PRODUCTOPTIONREMOVEDBY NUMBER,
        PRODUCTOPTIONREMOVEDON TIMESTAMP_NTZ,
        PRODUCTOPTIONUPDATEDON TIMESTAMP_NTZ,
        PRODUCTOPTIONUPDATEDBY NUMBER,
        PRODUCTOPTIONWASTEPERCENTAGE NUMBER(12,2),
        PRODUCTOPTIONPRICE NUMBER(12,2),
        PRODUCTOPTIONDISPLAYPRICE NUMBER(12,2),
        PRODUCTOPTIONIMAGEID NUMBER,
        PRODUCTOPTIONICONID NUMBER,
        PRODUCTOPTIONSORT NUMBER,
        PRODUCTOPTIONNOOFPIECE NUMBER,
        PRODUCTOPTIONSERVED NUMBER,
        PRODUCTOPTIONSTOREID NUMBER
    );

    ----------------------------------------------------------------
    -- BRONZE.USERS
    ----------------------------------------------------------------
    CREATE OR REPLACE TABLE MF_DWH.BRONZE.USERS (
        USERSID NUMBER,
        USERSNAME VARCHAR,
        USERSLASTNAME VARCHAR,
        USERSEMAIL VARCHAR,
        USERSMOBILE VARCHAR,
        USERSSTATUS NUMBER,
        USERSEMAILVERIFIED BOOLEAN,
        USERSMOBILEVERIFIED BOOLEAN,
        USERSADDEDON TIMESTAMP_NTZ,
        USERSUPDATEDON TIMESTAMP_NTZ,
        USERSREMOVEDON TIMESTAMP_NTZ,
        USERSPASSWORD VARCHAR,
        USERSSALT VARCHAR,
        USERSAUTHKEY VARCHAR,
        USERSAUTHEXPIREON TIMESTAMP_NTZ,
        USERSAUTHREFRESHTOKEN VARCHAR,
        USERSAUTHREFRESHTOKENEXPIREON TIMESTAMP_NTZ,
        USERSPASSWORDRESETTOKEN VARCHAR,
        USERSADDRESSID NUMBER,
        USERSADDEDBY NUMBER,
        USERSLASTLOGIN TIMESTAMP_NTZ,
        USERSLATITUDE VARCHAR,
        USERSLONGITUDE VARCHAR,
        USERSISADMIN BOOLEAN,
        USERSSUPPLIERID NUMBER,
        USERSSTOREID NUMBER,
        USERSWALLETBALANCE NUMBER(12,2),
        USERSTYPEID NUMBER,
        USERSDESIGNATION VARCHAR,
        USERPAYMENTMODES VARCHAR,
        USERSNEWSLETTER BOOLEAN,
        USERSFIREBASEID VARCHAR,
        USERSFREEDELIVERY BOOLEAN,
        USERSDELIVERYSTOREID NUMBER,
        USERSDELIVERYLOCATIONID NUMBER,
        USERSDOB DATE,
        ORDERCOUNT NUMBER
    );

    ----------------------------------------------------------------
    -- BRONZE.ADDRESS
    ----------------------------------------------------------------
    CREATE OR REPLACE TABLE MF_DWH.BRONZE.ADDRESS (
        ADDRESSID NUMBER,
        ADDRESSUSERID NUMBER,
        ADDRESSLINE VARCHAR,
        ADDRESSLINETWO VARCHAR,
        ADDRESSLINETHREE VARCHAR,
        ADDRESSPIN VARCHAR,
        ADDRESSCITY VARCHAR,
        ADDRESSDISTRICTID NUMBER,
        ADDRESSSTATEID NUMBER,
        ADDRESSCOUNTRYID NUMBER,
        ADDRESSTYPE NUMBER,
        ADDRESSUSERNAME VARCHAR,
        ADDRESSPHONE VARCHAR,
        ADDRESSLATITUDE VARCHAR,
        ADDRESSLONGITUDE VARCHAR,
        ADDRESSADDEDON TIMESTAMP_NTZ,
        ADDRESSADDEDBY NUMBER,
        ADDRESSREMOVEDON TIMESTAMP_NTZ,
        ADDRESSREMOVEDBY NUMBER,
        ADDRESSDELIVERYLOCATIONID NUMBER,
        ADDRESSDELIVERYLOCATIONID_OLD NUMBER
    );

    ----------------------------------------------------------------
    -- BRONZE.COUNTRY
    ----------------------------------------------------------------
    CREATE OR REPLACE TABLE MF_DWH.BRONZE.COUNTRY (
        COUNTRYID NUMBER,
        COUNTRYNAME VARCHAR,
        COUNTRYCURRENCY VARCHAR,
        COUNTRYCURRENCYSHORT VARCHAR,
        COUNTRYCURRENCYSYMBOL VARCHAR,
        COUNTRYMOBILEPREFIX VARCHAR,
        COUNTRYFLAGMEDIAID VARCHAR
    );

    ----------------------------------------------------------------
    -- BRONZE.STATES
    ----------------------------------------------------------------
    CREATE OR REPLACE TABLE MF_DWH.BRONZE.STATES (
        STATESID NUMBER,
        STATESNAME VARCHAR,
        STATESCOUNTRYID NUMBER,
        STATECODE VARCHAR,
        STATEGSTIN VARCHAR
    );

    ----------------------------------------------------------------
    -- BRONZE.DISTRICTS
    ----------------------------------------------------------------
    CREATE OR REPLACE TABLE MF_DWH.BRONZE.DISTRICTS (
        DISTRICTSID NUMBER,
        DISTRICTSNAME VARCHAR,
        DISTRICTSSTATEID NUMBER,
        DISTRICTSCOUNTRYID NUMBER,
        DISTRICTSPREFIX VARCHAR
    );

    ----------------------------------------------------------------
    -- BRONZE.DELIVERY_LOCATION
    ----------------------------------------------------------------
    CREATE OR REPLACE TABLE MF_DWH.BRONZE.DELIVERY_LOCATION (
        DELIVERYLOCATIONID NUMBER,
        DELIVERYLOCATIONSUPPLIERID NUMBER,
        DELIVERYLOCATIONPINCODE VARCHAR,
        DELIVERYLOCATIONDISTRICTID NUMBER,
        DELIVERYLOCATIONSTATEID NUMBER,
        DELIVERYLOCATIONADDEDON TIMESTAMP_NTZ,
        DELIVERYLOCATIONROUTEID NUMBER,
        DELIVERYLOCATIONREMOVEDON TIMESTAMP_NTZ,
        DELIVERYLOCATIONPLACE VARCHAR,
        DELIVERYLOCATIONSTOREID NUMBER,
        TEST VARCHAR
    );

    ----------------------------------------------------------------
    -- BRONZE.DELIVERY_SLOT
    ----------------------------------------------------------------
    CREATE OR REPLACE TABLE MF_DWH.BRONZE.DELIVERY_SLOT (
        DELIVERYSLOTID NUMBER,
        DELIVERYSLOTDESCRIPTION VARCHAR,
        DELIVERYSLOTSTARTTIME TIME,
        DELIVERYSLOTCUTOFFTIME TIME,
        DELIVERYSLOTENDTIME TIME,
        DELIVERYSLOTADDEDON TIMESTAMP_NTZ,
        DELIVERYSLOTREMOVEDON TIMESTAMP_NTZ,
        DELIVERYSLOTSUPPLIERID NUMBER,
        DELIVERYSLOTSTOREID NUMBER,
        DELIVERYSLOTTYPEID NUMBER
    );

    RETURN 'Bronze layer tables created successfully';

END;
$$;
